premiereAPI ; premiers TU
evan-boissonnot/cvgamifie.back pull request #1
Opened 2020-06-17 11:50 UTC by newtom69

first pull request of my life 😅

2020-06-18 08:34 UTC, evan-boissonnot requested changes
Je ne peux pas l'accepter, tu push sur la branch master. on est en dev pour l'instant :)

2020-06-18 09:43 UTC, newtom69 commented
> 
> 
> Je ne peux pas l'accepter, tu push sur la branch master. on est en dev pour l'instant :)

il faut que tu créé la branche dev. je n'ai pas d'autre option que master sinon

2020-06-18 10:17 UTC, evan-boissonnot commented
Thomas c'est fait :)

Bien cordialement
__________________________________________
Evan BOISSONNOT - Entrepreneur agile
Site : http://evanboissonnot.fr

Tel. : 06 10 37 52 10


*Je pratique l'écologie temporelle : je ne regarde mes mails qu'à 12h00
tous les jours (sauf le week-end). Je vous réponds donc au maximum dans une
journée.Si très important, appelez-moi :)*


Le jeu. 18 juin 2020 à 11:43, Thomas Vuille <notifications@github.com> a
écrit :

> Je ne peux pas l'accepter, tu push sur la branch master. on est en dev
> pour l'instant :)
>
> il faut que tu créé la branche dev. je n'ai pas d'autre option que master
> sinon
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/evan-boissonnot/cvgamifie.back/pull/1#issuecomment-645907439>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGK7AY6YMWQ5UYS3QOS7AO3RXHOT5ANCNFSM4OAQU4ZA>
> .
>

2020-06-18 10:46 UTC, evan-boissonnot commented
Je vous remercie d'avoir pris contact.

Votre demande est urgente ? 
Appelez-moi de suite au 06.10.37.52.10.

Je vous réponds dans une journée au plus tard.
_________________

Sent to reply@reply.github.com

Unsubscribe:
http://papaetpatron.acemlnb.com/proc.php?nl=3&c=92&m=201&s=b174c596a53e4c9d84fd45aae3efd01f&act=unsub

evan boissonnot, 17 la vinalière, 44850 le cellier, France

2020-06-20 10:06 UTC, evan-boissonnot approved these changes

2020-06-20 10:06 UTC, merged

2021-01-08 14:49 UTC, evan-boissonnot commented
Une très belle année 2021 !

Avec cette année 2020 qui vient de finir, on tourne une page d'une
année étrange ... avec des hauts, des bas ... en espérant que cette
année 2021 soit bien meilleure ! Et c'est tout le malheur que l'on se
souhaite, n'est-ce pas ?! :)

Je vous souhaite une très belle année 2021 ! Remplie de projets, de
bonheurs, de plaisirs partagés ! De cohésion dans vos équipes ! 

-----------------------------------------------------------------------------------------------------------------------

Et pour moi, l'année 2021 s'annonce prometteuse : 

- Très hâte de vous accompagner pour assurer la réussite de vos
projets informatiques : plus de cohésion technique, plus de cohésion
humaine ! 
> Tiens, en passant, vous aviez renseigné mon questionnaire pour mieux
vous connaître ? https://papaetpatron.lt.acemlnd.com/Prod/link-tracker?redirectUrl=aHR0cHMlM0ElMkYlMkZmb3Jtcy5nbGUlMkZjMThWOU1xUFo1UEhZMlZKOA==&a=251884939&account=papaetpatron%2Eactivehosted%2Ecom&email=uArP23b6OaWMrvkaih8x4KMivv2cXdh%2FCvMQSnVnCYcfRunTxziF%2BZna%2B2OiYkqZ%2FGKPQrHrYlT%2BzQx7qO26dvlMy%2BOWWuyaZunZiCXh6gI%3D&s=b174c596a53e4c9d84fd45aae3efd01f&i=190A248A3A1313

- Je vais compléter mon offre en me formant (j'ai un objectif de me
former à minima une fois par an) : formation pour valider mes
compétences de coach professionnel ! 

- Je continue bien entendu à transmettre à travers les formations
présentielles, et distancielles : angular, asp.net, blazor, mvc.net,
javascript, react, devops, agilité, ...

> Vous souhaitez améliorer les compétences de vos équipes ? 
Appelez-moi ! :)
06 10 37 52 10, ou evan@boissonnot.fr

-  Enfin, je vais développer une offre e-learning dédiée sur dotnet
5.0 et tout ce qui gravite autour de dotnet ! 
Si vous êtes intéressé-e, répondez à cet email :)

- Et, et ..... non pas des moindres : je vais enclencher ma
certification Qualiopi !

A très vite
Evan
_________________

Sent to reply@reply.github.com

Unsubscribe:
http://papaetpatron.activehosted.com/proc.php?nl=3&amp;c=190&amp;m=248&amp;s=b174c596a53e4c9d84fd45aae3efd01f&amp;act=unsub

evan boissonnot, 17 la vinalière, 44850 le cellier, France